<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Company>Jorge Macias</Company>
    <Description>Este programa permite exportar datos desde un .txt descargados desde Santander a Excel a petición.</Description>
    <Copyright>Jorge Macias</Copyright>
    <PackageProjectUrl>https://github.com/Jorgemacias-12/bank2xlsx</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Jorgemacias-12/bank2xlsx</RepositoryUrl>
    <ApplicationIcon>Resources\bank2xlsx.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\bank2xlsx.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
  </ItemGroup>

</Project>
