name: Build Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  APP_NAME: Bank2xlsx
  DOTNET_VERSION: net10.0-windows
  RUNTIME: win-x64

jobs:

  build:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: >
          dotnet publish
          -c Release
          -r ${{ env.RUNTIME }}
          --self-contained true
          /p:PublishSingleFile=true
          /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Zip Release
        run: >
          Compress-Archive
          -Path bin/Release/${{ env.DOTNET_VERSION }}/${{ env.RUNTIME }}/publish/${{ env.APP_NAME }}.exe
          -DestinationPath ${{ env.APP_NAME }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/Release/${{ env.DOTNET_VERSION }}/${{ env.RUNTIME }}/publish/${{ env.APP_NAME }}.exe
            ${{ env.APP_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}